---
name: CI
on:
  push:
    branches: [ '*' ]
jobs:
  run-tests-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 20, 22 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: Run tests with coverage
        run: | 
          npm ci
          npm run test:coverage
        working-directory: my-vue-app
  run-tests-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ 20, 22 ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: Run tests with coverage
        run: |
          npm ci
          npm run test:coverage
        working-directory: my-fastify-api
